services:
  db-standalone:
    image: postgres:17.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=establishment
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data
    networks:
      - config-store-net

networks:
  config-store-net:

volumes:
  postgres-data:
